travis:
  secure:
    BINSTAR_TOKEN: JXuIqcMnY2a6CNElMqafgi6QknJjOU7X//HS80ZgZKlJVZMdiYogwth/jYB3aUrVazcGqiMad608Cp5UU+GJWSrd679x7VD0IfhLv9tRBPlRcCnzKXlkCi7ZWhWS3Fyrr/ZF+Ehw5PNjWuIonWjrWDkEzWIM7GsoDRTxCCxAaG+63N3RAVW7c5/IqrgLqyadKKiGHHZJgPbWT8kmZqFxcLT+bekmKYd7n9zOus4DQhxVPo21MLjAEb6K7c+E+BAEHREnSsbrmovA7OKDBhtXen2//QaqIAFZ9R72ABJhMmLs7QxiCZ95zQA6EvBE33F3PVyz7VrSd9DZwDXh4moeLzTM5LZ0TVylj8Dwjf5nJdZZc+XcftjiY5BmfZMYXyn9zClYq8vXNEAPzGo1lV8uXapJnWwQR21AviDQFw7cMcjInc8FjaUTpQ3ahnSWN7yu030PRht+wsbxSm+AA52AvMmbcaKceSn/6xmBGugbtEQje3CBOL0ICiIEWOysn1eqCVj+oW0iAqVhphuHobCx+vvbEvoDkMVmmgiBrd7y/3Jr1+cB0zM79BjhVdP+bXc14PTUVLUQFRoEl4JFc8JcoLL5bcb4Rg8YXtdaTdr7eji3MD4pdWvmNmc7kI5mrEV1Tfs5gIgzwTaJbRMK3AROzpn2vqxMa0bxBrOa9JC6LsE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
